### ISSUE TITLE
Permission denied Error

### ISSUE THREAD

**Issue by pulpyboy0130** [kylierst/MSO_E5_Dev_AutoRenew_REVISION_2#3]
Run ad-m/github-push-action@v0.6.0
Started: bash /home/runner/work/_actions/ad-m/github-push-action/v0.6.0/start.sh
Push to branch refs/heads/main
remote: Permission to pulpyboy0[13](https://github.com/pulpyboy0130/MSO_E5_Dev_AutoRenew_REVISION_2/actions/runs/4355136457/jobs/7611345909#step:9:14)0/MSO_E5_Dev_AutoRenew_REVISION_2.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/pulpyboy0130/MSO_E5_Dev_AutoRenew_REVISION_2.git/': The requested URL returned error: 403
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/v0.6.0/start.js:9:19)
    at ChildProcess.emit (events.js:3[14](https://github.com/pulpyboy0130/MSO_E5_Dev_AutoRenew_REVISION_2/actions/runs/4355136457/jobs/7611345909#step:9:15):20)
    at maybeClose (internal/child_process.js:1022:[16](https://github.com/pulpyboy0130/MSO_E5_Dev_AutoRenew_REVISION_2/actions/runs/4355136457/jobs/7611345909#step:9:17))
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/v0.6.0/start.js:9:[19](https://github.com/pulpyboy0130/MSO_E5_Dev_AutoRenew_REVISION_2/actions/runs/4355136457/jobs/7611345909#step:9:20))
    at ChildProcess.emit (events.js:314:[20](https://github.com/pulpyboy0130/MSO_E5_Dev_AutoRenew_REVISION_2/actions/runs/4355136457/jobs/7611345909#step:9:21))
    at maybeClose (internal/child_process.js:10[22](https://github.com/pulpyboy0130/MSO_E5_Dev_AutoRenew_REVISION_2/actions/runs/4355136457/jobs/7611345909#step:9:23):16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:[28](https://github.com/pulpyboy0130/MSO_E5_Dev_AutoRenew_REVISION_2/actions/runs/4355136457/jobs/7611345909#step:9:29)7:5)

**Comment by kylierst** [comment]
Did you follow this part of the tutorial? 
Go to your personal settings page (Settings in the top right header, not Settings in the repository) and select Developer settings > Personal access tokens > Generate new token, Generate new token Set the name to GITHUB_TOKEN , then check the options repo , admin:repo_hook , workflow , etc., and finally click Generate token.

**Comment by pulpyboy0130** [comment]
Yes, I was follow your instruction include create personal access token with GITHUB_TOKEN name

**Comment by kylierst** [comment]
please double check if you gave the proper permissions. The only way that this error will occur is due to lack of permission of the Github action bot to the repo.
Refer here for more information https://github.com/ad-m/github-push-action/issues/96

**Comment by kylierst** [comment]
Check if "Read and write permissions" are enabled in Settings -> Actions -> General -> Workflow permissions:
![image](https://user-images.githubusercontent.com/22324149/223488932-1d22cbe6-c90e-4cb9-9647-f941e83a75e8.png)

**Comment by pulpyboy0130** [comment]
Now working bro... Thanks, lot. Yes I do the same

**Comment by kylierst** [comment]
Okay. Nice!
